using Ardalis.SharedKernel;

namespace Domain.Aggrgates.LocationAggregate;

public class Location : EntityBase, IAggregateRoot
{
    // Needed for EF
    private Location() : this(null!) { }

    public Location(string portCode)
    {
        PortCode = portCode;
    }

    /// <summary>
    /// Readonly is not allowed in EF, it will be ignored (no field generated in SQL)
    /// </summary>
    public string PortCode { get; private set; }

    ///// <summary>
    ///// Key -> auto generated by EF
    ///// </summary>
    ///*
    //    Location: Two places with the same name are not the same. Latitude and longitude could
    //    provide a unique key, but probably not a very practical one, since it is not of interest to
    //    most purposes of this system, and would be fairly complicated. More likely, the Location
    //    will be part of a geographical model of some kind that will relate places, and an arbitrary,
    //    internal, automatically generated identifier will suffice 
    //*/
    //public int Id { get; private set; }
}
