using Ardalis.SharedKernel;

namespace Domain.Aggrgates.CustomerAggregate;

public class Customer : EntityBase, IAggregateRoot // QUESTION: what is the difference between root and base?
{
    ///// <summary>
    ///// Key -> auto generated by EF
    ///// Identity: this is known in the outside
    ///// </summary>
    //public int CustomerId { get; }
    public string Name { get; private set; }
    // Needed for EF
    private Customer() : this(string.Empty) {}

    internal Customer(string name)
    {
        Name = name;
    }    
    
    public void ChangeName(string name)
    {
        Name = name;
    }
}
